# Generated by Django 4.1.3 on 2023-04-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_appointment_service_appointment_user2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='agenda',
            field=models.CharField(default='No Agenda', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='No Title', max_length=20),
        ),
    ]
